# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='\u0425\u0430\u0440\u0438\u0443\u043b\u0442')),
            ],
            options={
                'db_table': 'answer',
                'verbose_name': '\u0425\u0430\u0440\u0438\u0443\u043b\u0442',
                'verbose_name_plural': '\u0425\u0430\u0440\u0438\u0443\u043b\u0442\u0443\u0443\u0434',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u0421\u0430\u043b\u0431\u0430\u0440\u044b\u043d \u043d\u044d\u0440')),
                ('phone_number', models.IntegerField(verbose_name='\u0423\u0442\u0430\u0441\u043d\u044b \u0434\u0443\u0433\u0430\u0430\u0440')),
                ('address', models.CharField(max_length=200, verbose_name='\u0425\u0430\u044f\u0433')),
                ('location', models.CharField(max_length=200, verbose_name='\u0411\u0430\u0439\u0440\u043b\u0430\u043b')),
                ('profile_image', models.ImageField(upload_to='branch/profile_pictures', verbose_name='\u0421\u0430\u043b\u0431\u0430\u0440\u044b\u043d profile \u0437\u0443\u0440\u0430\u0433')),
            ],
            options={
                'db_table': 'branch',
                'verbose_name': '\u0421\u0430\u043b\u0431\u0430\u0440',
                'verbose_name_plural': '\u0421\u0430\u043b\u0431\u0430\u0440\u0443\u0443\u0434',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u0410\u043d\u0433\u0438\u043b\u0430\u043b\u044b\u043d \u043d\u044d\u0440')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': '\u0410\u043d\u0433\u0438\u043b\u0430\u043b',
                'verbose_name_plural': '\u0410\u043d\u0433\u0438\u043b\u0430\u043b\u0443\u0443\u0434',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u0411\u0430\u0439\u0433\u0443\u0443\u043b\u043b\u0430\u0433\u044b\u043d \u043d\u044d\u0440')),
                ('url', models.URLField(verbose_name='\u0412\u0435\u0431 \u0421\u0430\u0439\u0442')),
                ('cover', models.ImageField(upload_to='organisation/covers', verbose_name='Cover \u0417\u0443\u0440\u0430\u0433')),
                ('profile_image', models.ImageField(upload_to='organisation/profile_pictures', verbose_name='Profile \u0417\u0443\u0440\u0430\u0433')),
                ('description', models.TextField(verbose_name='\u0422\u0430\u043d\u0438\u043b\u0446\u0443\u0443\u043b\u0433\u0430')),
            ],
            options={
                'db_table': 'organisation',
                'verbose_name': '\u0411\u0430\u0439\u0433\u0443\u0443\u043b\u043b\u0430\u0433\u0430',
                'verbose_name_plural': '\u0411\u0430\u0439\u0433\u0443\u0443\u043b\u043b\u0430\u0433\u0443\u0443\u0434',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u0411\u0430\u0440\u0430\u0430\u043d\u044b \u043d\u044d\u0440')),
                ('price', models.CharField(max_length=200, verbose_name='\u04ae\u043d\u044d')),
                ('details', models.TextField(verbose_name='\u0414\u044d\u043b\u0433\u044d\u0440\u044d\u043d\u0433\u04af\u0439')),
                ('rating', models.IntegerField(verbose_name='\u04ae\u043d\u044d\u043b\u0433\u044d\u044d')),
                ('picture', models.ImageField(upload_to='product/picture')),
            ],
            options={
                'db_table': 'product',
                'verbose_name': '\u0411\u0430\u0440\u0430\u0430',
                'verbose_name_plural': '\u0411\u0430\u0440\u0430\u0430\u043d\u0443\u0443\u0434',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='\u0410\u0441\u0443\u0443\u043b\u0442')),
            ],
            options={
                'db_table': 'question',
                'verbose_name': '\u0410\u0441\u0443\u0443\u043b\u0442',
                'verbose_name_plural': '\u0410\u0441\u0443\u0443\u043b\u0442\u0443\u0443\u0434',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='\u0425\u044f\u043c\u0434\u0440\u0430\u043b \u044d\u0445\u044d\u043b\u0441\u044d\u043d \u04e9\u0434\u04e9\u0440')),
                ('finish_date', models.DateField(verbose_name='\u0425\u044f\u043c\u0434\u0440\u0430\u043b \u0434\u0443\u0443\u0441\u0430\u0445 \u04e9\u0434\u04e9\u0440')),
                ('precent', models.FloatField(verbose_name='\u0425\u0443\u0432\u044c')),
                ('thumbnail', models.ImageField(upload_to='sale/thumbnail', verbose_name='\u0417\u0443\u0440\u0430\u0433')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u044d\u0440')),
                ('avatar', models.ImageField(default='', upload_to='sale/avatar', verbose_name='Avatar')),
                ('price', models.CharField(max_length=200, verbose_name='\u04ae\u043d\u044d')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Product')),
            ],
            options={
                'db_table': 'sale',
                'verbose_name': '\u0425\u044f\u043c\u0434\u0440\u0430\u043b',
                'verbose_name_plural': '\u0425\u044f\u043c\u0434\u0440\u0430\u043b\u0443\u0443\u0434',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u0414\u044d\u0434 \u0430\u043d\u0433\u0438\u043b\u0430\u043b\u044b\u043d \u043d\u044d\u0440')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Category')),
            ],
            options={
                'db_table': 'subcategory',
                'verbose_name': '\u0414\u044d\u0434 \u0430\u043d\u0433\u0438\u043b\u0430\u043b',
                'verbose_name_plural': '\u0414\u044d\u0434 \u0430\u043d\u0433\u0438\u043b\u0430\u043b\u0443\u0443\u0434',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='\u041d\u044d\u0440')),
                ('lastname', models.CharField(max_length=200, verbose_name='\u041e\u0432\u043e\u0433')),
                ('email', models.EmailField(max_length=254, verbose_name='\u0418-\u043c\u044d\u0439\u043b \u0445\u0430\u044f\u0433')),
                ('password', models.CharField(max_length=200, verbose_name='\u041d\u0443\u0443\u0446 \u04af\u0433')),
                ('image', models.ImageField(default='user/images/avatar-placeholder.png', upload_to='user/images', verbose_name='\u0417\u0443\u0440\u0430\u0433')),
                ('following_orginisations', models.ManyToManyField(related_name='following', to='groupon_models.Organisation', verbose_name='\u0414\u0430\u0433\u0430\u0436 \u0431\u0443\u0439 \u0431\u0430\u0439\u0433\u0443\u0443\u043b\u0433\u0443\u0443\u0434')),
                ('save_sale', models.ManyToManyField(to='groupon_models.Sale', verbose_name='\u0425\u0430\u0434\u0433\u0430\u043b\u0441\u0430\u043d \u0445\u044f\u043c\u0434\u0440\u0430\u043b')),
            ],
            options={
                'db_table': 'user',
                'verbose_name': '\u0425\u044d\u0440\u044d\u0433\u043b\u044d\u0433\u0447',
                'verbose_name_plural': '\u0425\u044d\u0440\u044d\u0433\u043b\u044d\u0433\u0447\u0438\u0434',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200, verbose_name='\u04ae\u043d\u044d\u043b\u0433\u044d\u044d')),
                ('comment', models.CharField(max_length=200, verbose_name='\u0421\u044d\u0442\u0433\u044d\u0433\u0434\u044d\u043b')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.User')),
            ],
            options={
                'db_table': 'review',
                'verbose_name': '\u0428\u04af\u04af\u043c\u0436',
                'verbose_name_plural': '\u0428\u04af\u04af\u043c\u0436\u04af\u04af\u0434',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Sale'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.SubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.User'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='groupon_models.User', verbose_name='\u0425\u044d\u0440\u044d\u0433\u043b\u044d\u0433\u0447'),
        ),
        migrations.AddField(
            model_name='branch',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Organisation'),
        ),
        migrations.AddField(
            model_name='branch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Product'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Question'),
        ),
    ]
