# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupon_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groupon_models.Organisation'),
        ),
        migrations.AddField(
            model_name='sale',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groupon_models.SubCategory'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='finish_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u0425\u044f\u043c\u0434\u0440\u0430\u043b \u0434\u0443\u0443\u0441\u0430\u0445 \u04e9\u0434\u04e9\u0440'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u0425\u044f\u043c\u0434\u0440\u0430\u043b \u044d\u0445\u044d\u043b\u0441\u044d\u043d \u04e9\u0434\u04e9\u0440'),
        ),
    ]
