# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupon_models', '0003_auto_20160704_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/images', verbose_name='\u0410\u043d\u0433\u0438\u043b\u0430\u043b\u044b\u043d \u0437\u0443\u0440\u0430\u0433'),
        ),
    ]
