# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupon_models', '0005_auto_20160705_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0422\u0430\u0439\u043b\u0431\u0430\u0440'),
        ),
    ]
