# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupon_models', '0006_branch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='save_sale',
            field=models.ManyToManyField(null=True, to='groupon_models.Sale', verbose_name='\u0425\u0430\u0434\u0433\u0430\u043b\u0441\u0430\u043d \u0445\u044f\u043c\u0434\u0440\u0430\u043b'),
        ),
    ]
