# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupon_models', '0007_auto_20160705_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='cover',
            field=models.ImageField(null=True, upload_to='branch/cover', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='user',
            name='save_sale',
            field=models.ManyToManyField(to='groupon_models.Sale', verbose_name='\u0425\u0430\u0434\u0433\u0430\u043b\u0441\u0430\u043d \u0445\u044f\u043c\u0434\u0440\u0430\u043b'),
        ),
    ]
